### PR TITLE
Concordia'/minor fixes

### LINKED ISSUE #91: Issuer&Verifier text issues/improvements
**Bug Description**
1. Add paragraph beneath the head title about what is the purpose of Concordia, why do we do this. Try to relate why is it necessary to pick minimum two attributes to get verified.
3. Title of the page is SoMe Verifier while should be Concordia
4. Text in the beginning missing "in" in "log in to the platform"
5. Add a text next to the Reveal name attribute something like: account on chain is required. Mainly because users could end up with Web3 credentials but without Mainnet account.

### PR DESCRIPTION
**Pull request by soerenbf**
## Purpose

Various small fixes

Closes #91

## Changes

- Add about page (same link as terms, different section)
- Move injected configs to document head
- Verfiier footer UI scaling (doesn't look broken on mobile)

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: examples/some-verifier/frontend/src/components/Verify.tsx [hunk 1]
```diff
@@ -247,6 +242,20 @@ export default function Verify() {
                 wallet. Additionally, you can also choose to reveal your full
                 name from an identity in your wallet.
               </p>
+              <p>
+                <strong>
+                  If these credentials do not exists in you wallet yet, go the
```
Comment (abizjak) [inline examples/some-verifier/frontend/src/components/Verify.tsx:247]:
```suggestion
                  If these credentials do not exists in you wallet yet, go to
```

**Review by abizjak — APPROVED** [review]

**Comment by abizjak** [comment]
Can we please bump versions in package.json of the verifier and issuer frontends.
